---
# These tasks install apache2 and the proxy modules and set up the www.elevateyourhit.com site vhost.

- name: Install apache2 and lynx
  apt: name={{ item }} state=present
  with_items:
   - apache2
   - lynx

#- name: Enable proxy, proxy_http, proxy_balancer and lbmethod_byrequests apache modules.
#  apache2_module: name={{ item }} state=present
#  with_items:
#    - proxy
#    - proxy_http
#    - proxy_balancer
#    - lbmethod_byrequests
#  notify: restart apache2

- name: Ensure httpd service is running and will run after reboot
  service: name=apache2 state=started enabled=yes
